-- AlterTable
ALTER TABLE "StoreSettings"
ADD COLUMN "name" TEXT NOT NULL DEFAULT 'Virtual Space',
ADD COLUMN "description" TEXT NOT NULL DEFAULT '',
ADD COLUMN "contacts" JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN "socials" JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "StoreSettings"
ALTER COLUMN "name" DROP DEFAULT,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "contacts" DROP DEFAULT,
ALTER COLUMN "socials" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;
